### ISSUE TITLE
Programm beendet nicht regelhaft bei fehlendem Data Ordner

### ISSUE THREAD

**Issue by EJochmann** [JesseRed/Elisabeth_Scheiben_game#1]
Ordner könnte direkt mit im Repo liegen. Alternativ: beim Schreiben des Ergebnis-Files Existenz des Ordners vorher prüfen und ggf. anlegen.

**Comment by EJochmann** [comment]
--> Data Ordner im Build händisch anlegen!

**Comment by JesseRed** [comment]
es gibt nun einen StreamingAssets
Ordner in Unity 
In diesem sind die Ordner Data und Experimental Design
Die werden bei jedem Build automatisch mit kopiert in den Build
