### ISSUE TITLE
WICHTIG: Esc schließt Programm und nichts wird gespeichert

### ISSUE THREAD

**Issue by EJochmann** [JesseRed/Elisabeth_Scheiben_game#13]
bitte wieder rausnehmen um Datenverlust bei versehentlichem Esc drücken zu vermeiden

**Comment by EJochmann** [comment]
bei Drücken von Esc zu egal welchem ZEitpunkt werden keine Daten gespeichert. Space button am Ende scheint obligatorisch für Speicherung. Bitte ZWischenspeicher zw. jedem Durchgang (s. extra Issue)

**Comment by JesseRed** [comment]
Wird denn nicht bei jedem Block gespeichert?
dachte das waere so ...
das bei Esc nicht gespeichert wird ist klar denn ich kann nur nach einem
Block speichern
der letzte Block sollte gespeichert sein
Innerhalb eines Blocks zu speichern waere sehr sehr komplex da verschiedene
SCheiben kreiert und nicht destroyed sind

Am So., 27. Sept. 2020 um 22:09 Uhr schrieb EJochmann <
notifications@github.com>:

**Comment by EJochmann** [comment]
Du hast Recht. Hab es gerade nochmal durchgetestet. Nach dem ersten Block wird das Dokument angelegt und die folgenden Blöcke daruntergesetzt.
Mir sind die Daten eines ganzen Tests abhanden gekommen und ich habe es auf ein mögliches falsches Schließen zurückgeführt - muss aber wohl doch eine andere Ursache haben. Da komme ich aber nicht drauf. Gelöscht ist nichts.
