### ISSUE TITLE
Bedeutung "Scheiben Nummer (in Sequence)" (in csv immer 0)

### ISSUE THREAD

**Issue by EJochmann** [JesseRed/Elisabeth_Scheiben_game#3]

**Comment by JesseRed** [comment]
die ist nur relevant wenn man ein Paradigma mit einer festen Anzahl von Scheiben nimmt statt wie jetzt ueber die Zeit
das Problem ist letztlich doch recht komplex ... welche Scheibenzahl nimmt man ... die created? die presented? vor allem wenn sich mehrere Scheiben gleichzeitig auf dem Bildschirm befinden und die 2. z.B. eine kuerzere LEbenszeit hat als die erste ...
