### ISSUE TITLE
Scheiben verschwinden mit Verzögerung von 1-2 Sekunden 

### ISSUE THREAD

**Issue by EJochmann** [JesseRed/Elisabeth_Scheiben_game#7]
→ Scheiben nach Hit sofort verschwinden lassen, sonst irritierend, weil manchmal 3 oder 4 Scheiben parallel sichtbar

**Comment by JesseRed** [comment]
es gibt nun im Paradigma.json file die Option "timeBetweenHitAndDisappear"
Angabe in sekunden
da kann man das nun einstellen ... der rote Punkt bleibt 100 ms laenger ... fand ich gut kann ich aber auch aendern
