### ISSUE TITLE
Pause Option notwendig → Esc → Zurück zum Spiel/Exit (was passiert mit CSV?)

### ISSUE THREAD

**Issue by EJochmann** [JesseRed/Elisabeth_Scheiben_game#9]

**Comment by JesseRed** [comment]
in der Pause zwischen den Bloecken gibt es nun mit Space eine PausenFunktion
mit erneutem Space geht es dann weiter
ESC beendet das Program
ich habe lange rumgetueftelt an einer Pause in dem Block ... aber das ist extrem komplex, da je nach paradigma multiple Scheiben in parallelen Coroutinen instanziert werden, dann muss man deren jeweilige Zeiten und die pausenlaengen tracken ... wenn das nicht von fundamentaler Bedeutung ist wuerde ich diese Funktion weg lassen
die Implementation wuerde dann auch noch erhebliches Testen erfordern weil sehr viele Parameter veraendert werdern
